#!/usr/bin/env bash
# A script to manage a process

PID_FILE="/var/run/my_process.pid"

case $1 in
    start)
        if [[ -f "$PID_FILE" ]]; then
            echo "manage_my_process is already running."
            exit 1
        fi
        ./manage_my_process &
        echo "$!" > "$PID_FILE"
        echo "manage_my_process started";;
    
    stop)
        if [[ -f "$PID_FILE" ]]; then
            PID=$(cat "$PID_FILE")
            if kill "$PID" 2>/dev/null; then
                rm "$PID_FILE"
                echo "manage_my_process stopped"
            else
                echo "Failed to stop manage_my_process. It may not be running."
            fi
        else
            echo "manage_my_process is not running."
        fi;;
    
    restart)
        if [[ -f "$PID_FILE" ]]; then
            PID=$(cat "$PID_FILE")
            if kill "$PID" 2>/dev/null; then
                rm "$PID_FILE"
            else
                echo "Failed to stop manage_my_process. It may not be running."
            fi
        fi
        ./manage_my_process &
        echo "$!" > "$PID_FILE"
        echo "manage_my_process restarted";;
    
    *)
        echo "Usage: manage_my_process {start|stop|restart}";;
esac
