#!/usr/bin/env bash
# A script to manage the manage_my_process daemon

PID_FILE="/var/run/my_process.pid"

start() {
    if [[ -f "$PID_FILE" ]]; then
        echo "manage_my_process is already running."
        exit 1
    fi
    ./manage_my_process &
    echo "$!" > "$PID_FILE"
    echo "manage_my_process started."
}

stop() {
    if [[ ! -f "$PID_FILE" ]]; then
        echo "manage_my_process is not running."
        return
    fi
    
    PID=$(cat "$PID_FILE")
    if kill "$PID" 2>/dev/null; then
        rm "$PID_FILE"
        echo "manage_my_process stopped."
    else
        echo "Failed to stop manage_my_process. It may not be running."
    fi
}

restart() {
    stop
    start
}

case $1 in
    start)
        start;;
    
    stop)
        stop;;
    
    restart)
        restart;;
    
    *)
        echo "Usage: manage_my_process {start|stop|restart}";;
esac
