#!/usr/bin/env bash
# This script indefinitely writes "I am alive!" to /tmp/my_process
while true
do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done

# Init script for manage_my_process

PIDFILE="/var/run/my_process.pid"
SCRIPT="./manage_my_process"

start() {
    if [ -f "$PIDFILE" ]; then
        echo "manage_my_process is already running."
    else
        $SCRIPT &
        echo $! > "$PIDFILE"
        echo "manage_my_process started"
    fi
}

stop() {
    if [ -f "$PIDFILE" ]; then
        pid=$(cat "$PIDFILE")
        kill "$pid"
        rm "$PIDFILE"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0